version: '2'
services:
    jlctest:
        build:
            context: .
        image:
            jlc_template:latest
        tty: true
        environment:
            PYTHONIOENCODING: utf-8
            CLASSPATH: "/work:/work/Cup/"
            DEPLOY: DEVDOCKER
            NOSE_NOCAPTURE: 1
        ports:
            - "80:80"
            - "8000:8000"
        volumes:
            - "/root/.ssh/:/root/.ssh/"
            - "./:/work/"
        # command:
        #     cd /work/ && make && cd tester && make && ./Grade ..
